"""Generate the Dart integration_test that drives capture.

Given a validated `ShotgunConfig`, emits a single `_shotgun_generated.dart`
file containing one `testWidgets` per (device, locale, scene) tuple. The
file is written into the user's `integration_test/` folder and is meant to
be regenerated on every `shotgun capture` run.
"""

from __future__ import annotations

from pathlib import Path

from jinja2 import Environment, StrictUndefined

from .config import ShotgunConfig

_TEMPLATE = """\
// GENERATED by `shotgun capture` — do not edit by hand.
// Regenerated from shotgun.yaml on every run.

import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:integration_test/integration_test.dart';
import 'package:shotgun_runner/shotgun_runner.dart';
import 'package:{{ package }}/{{ entry_basename }}';
{%- if setup_import %}
import '{{ setup_import }}' as _shotgun_setup;
{%- endif %}

const _shots = <_Shot>[
{%- for shot in shots %}
  _Shot(
    platform: '{{ shot.platform }}',
    deviceName: '{{ shot.device.name }}',
    width: {{ shot.device.size[0] }}.0,
    height: {{ shot.device.size[1] }}.0,
    locale: '{{ shot.locale }}',
    sceneId: '{{ shot.scene.id }}',
    route: '{{ shot.scene.route }}',
    index: {{ shot.index }},
  ),
{%- endfor %}
];

class _Shot {
  const _Shot({
    required this.platform,
    required this.deviceName,
    required this.width,
    required this.height,
    required this.locale,
    required this.sceneId,
    required this.route,
    required this.index,
  });
  final String platform;
  final String deviceName;
  final double width;
  final double height;
  final String locale;
  final String sceneId;
  final String route;
  final int index;
}

void main() {
  IntegrationTestWidgetsFlutterBinding.ensureInitialized();
{%- if setup_import %}
  _shotgun_setup.{{ setup_fn }}();
{%- endif %}

  for (final shot in _shots) {
    testWidgets(
      '${shot.platform}/${shot.deviceName}/${shot.locale}/${shot.sceneId}',
      (tester) async {
        final device = ShotgunDevice(
          platform: shot.platform,
          name: shot.deviceName,
          width: shot.width,
          height: shot.height,
        );
        ShotgunCapture.setLocale(tester, shot.locale);
        await ShotgunCapture.resizeFor(tester, device);
        await tester.pumpWidget(
          ShotgunCapture.framedApp(const {{ root_widget }}()),
        );
        await tester.pumpAndSettle();
        await ShotgunCapture.navigateTo(tester, shot.route);
        await ShotgunCapture.capture(
          device: device,
          locale: shot.locale,
          sceneId: shot.sceneId,
          fileName: '${shot.index.toString().padLeft(2, '0')}_${shot.sceneId}',
        );
      },
    );
  }
}
"""


def _flutter_package_name(project_root: Path) -> str:
    """Read the Flutter app's package name from its pubspec.yaml."""
    pubspec = project_root / "pubspec.yaml"
    if not pubspec.exists():
        raise FileNotFoundError(f"no pubspec.yaml at {pubspec}")
    for line in pubspec.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if stripped.startswith("name:"):
            return stripped.split(":", 1)[1].strip().strip('"').strip("'")
    raise ValueError(f"{pubspec}: no `name:` field found")


def _setup_import_path(config: ShotgunConfig, project_root: Path) -> str | None:
    """Resolve `app.setup_file` to an import path usable from
    `integration_test/_shotgun_generated.dart`.

    Files inside `integration_test/` are imported with a relative path
    (`integration_test/` is not a Dart package directory). Files inside
    `lib/` are imported via `package:<name>/...`.
    """
    if not config.app.setup_file:
        return None
    setup_path = (project_root / config.app.setup_file).resolve()
    generated_dir = (project_root / "integration_test").resolve()
    try:
        rel = setup_path.relative_to(generated_dir)
        return rel.as_posix()
    except ValueError:
        pass
    lib_dir = (project_root / "lib").resolve()
    try:
        rel = setup_path.relative_to(lib_dir)
        package = config.app.package or _flutter_package_name(project_root)
        return f"package:{package}/{rel.as_posix()}"
    except ValueError as exc:
        raise ValueError(
            f"app.setup_file {config.app.setup_file!r} must live under "
            f"integration_test/ or lib/"
        ) from exc


def render_integration_test(config: ShotgunConfig, project_root: Path) -> str:
    """Return the Dart source code for `_shotgun_generated.dart`."""
    package = config.app.package or _flutter_package_name(project_root)
    entry_basename = Path(config.app.entry).name  # e.g. main.dart
    env = Environment(
        autoescape=False,
        keep_trailing_newline=True,
        undefined=StrictUndefined,
        trim_blocks=False,
        lstrip_blocks=False,
    )
    tmpl = env.from_string(_TEMPLATE)
    return tmpl.render(
        package=package,
        entry_basename=entry_basename,
        root_widget=config.app.root_widget,
        shots=config.iter_matrix(),
        setup_import=_setup_import_path(config, project_root),
        setup_fn=config.app.setup_fn,
    )


def write_integration_test(config: ShotgunConfig, project_root: Path) -> Path:
    """Write the generated test to `integration_test/_shotgun_generated.dart`."""
    code = render_integration_test(config, project_root)
    out_dir = project_root / "integration_test"
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / "_shotgun_generated.dart"
    out_path.write_text(code, encoding="utf-8")
    return out_path
